/* GENERATED by scripts/bake-atlas-poster.py; do not edit. The world rectangle public/atlas/poster.webp spans. */
export const POSTER_FRAME = {
  minX: -0.093721,
  minY: 0.104186,
  maxX: 1.093721,
  maxY: 0.895814,
  width: 2400,
  height: 1600,
  asOf: '2026-09',
} as const;
