"""
Turns the Higgsfield masters in assets-src/atlas/ into the files the atlas
renderer loads, and bakes the island land masks the layout uses.

    python scripts/prepare-atlas-assets.py

For every master PNG:
  1. crop to the alpha bounding box plus a small margin, so the subject fills
     its sprite and a world radius maps onto the painting predictably;
  2. pad to a square around the bounding-box centre;
  3. resize to the size the sprite is drawn at, and save as WebP with alpha
     under public/atlas/ (a 2048px island is ~0.5 MB instead of 6 MB).

For the seven islands it also downsamples the cropped alpha to a coarse grid
and writes src/atlas/masks.ts, so placeSettlements can keep settlements on
land without decoding images at runtime or in node.

Masters stay in assets-src/ (gitignored, like the video masters); regenerate
them from public/atlas/PROMPTS.md. Needs Pillow.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets-src" / "atlas"
OUT = ROOT / "public" / "atlas"
MASKS = ROOT / "src" / "atlas" / "masks.ts"

MASK_SIZE = 48
MARGIN = 0.03  # of the larger bounding-box side, kept around the subject
QUALITY = 88

# Output size per file. Islands drawn large get 2048; islets, sprites and
# icons never cover that many screen pixels.
SIZES: dict[str, int] = {
    "island-jailau": 2048,
    "island-tasqyr": 2048,
    "island-qaragai": 2048,
    "island-tikjar": 2048,
    "island-qumtobe": 1536,
    "island-ottas": 1024,
    "island-sazkol": 1024,
    "settlement-fortress": 768,
    "settlement-walled-town": 768,
    "settlement-market-town": 768,
    "settlement-hamlet": 640,
    "settlement-ruin": 640,
    "crown": 256,
    "pennant": 256,
    "glow": 512,
    "lighthouse": 512,
    "windmill-tower": 512,
    "windmill-sails": 512,
    "gull": 256,
    "boat": 384,
}


def square_crop(image: Image.Image) -> Image.Image:
    """Crop to the alpha bounding box with a margin, then pad to a square."""
    alpha = image.getchannel("A")
    box = alpha.getbbox()
    if box is None:
        raise SystemExit(f"{image.filename}: fully transparent")
    left, top, right, bottom = box
    width, height = right - left, bottom - top
    side = int(max(width, height) * (1 + 2 * MARGIN))
    cx, cy = (left + right) / 2, (top + bottom) / 2
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.paste(image.crop(box), (round(side / 2 - width / 2), round(side / 2 - height / 2)))
    return square


def land_mask(square: Image.Image) -> list[str]:
    """MASK_SIZE rows of '0'/'1': a cell is land when its mean alpha passes 50%."""
    small = square.getchannel("A").resize((MASK_SIZE, MASK_SIZE), Image.Resampling.BOX)
    pixels = small.load()
    return [
        "".join("1" if pixels[x, y] >= 128 else "0" for x in range(MASK_SIZE))
        for y in range(MASK_SIZE)
    ]


def main() -> None:
    if not SRC.is_dir():
        sys.exit(f"no masters in {SRC}")
    OUT.mkdir(parents=True, exist_ok=True)
    masks: dict[str, list[str]] = {}
    for path in sorted(SRC.glob("*.png")):
        name = path.stem
        size = SIZES.get(name)
        if size is None:
            print(f"skip {name}: no size configured")
            continue
        image = Image.open(path)
        if name == "glow":
            # Drawn additively on its black ground; no alpha, no crop.
            prepared = image.convert("RGB")
        else:
            prepared = square_crop(image.convert("RGBA"))
            if name.startswith("island-"):
                masks[name.removeprefix("island-")] = land_mask(prepared)
        prepared = prepared.resize((size, size), Image.Resampling.LANCZOS)
        target = OUT / f"{name}.webp"
        prepared.save(target, "WEBP", quality=QUALITY, method=6)
        print(f"{name:24s} {image.size[0]}x{image.size[1]} -> {size}x{size}  {target.stat().st_size / 1024:6.0f} KB")

    lines = [
        "/*",
        " * Generated by scripts/prepare-atlas-assets.py from the island paintings'",
        " * alpha channel: one row per grid line, '1' where the painting is land.",
        " * The grid spans the painting's square sprite. Do not edit by hand.",
        " */",
        "",
        f"export const MASK_SIZE = {MASK_SIZE};",
        "",
        "export const ISLAND_MASKS: Record<string, readonly string[]> = {",
    ]
    for island, rows in sorted(masks.items()):
        lines.append(f"  {island}: [")
        lines.extend(f"    '{row}'," for row in rows)
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    MASKS.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {MASKS.relative_to(ROOT)} for {len(masks)} islands")


if __name__ == "__main__":
    main()
